# -*- coding: utf-8 -*-
"""model_download.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y_JvDuAVDbA_d7NCISXd_6nbyLn3yDZa
"""

import os

# Check if the model is already downloaded
if not os.path.exists('lid.176.bin'):
    print("Downloading fastText language detection model...")
    os.system('wget https://dl.fbaipublicfiles.com/fasttext/supervised-models/lid.176.bin')